### ISSUE TITLE
Shell360_0.0.7_x64 Windows 11，设置选项里双击主题右侧按钮导致程序崩溃

### ISSUE THREAD

**Issue by fzhw88** [shell360/release#4]
![截图](https://github.com/user-attachments/assets/509cda39-b64b-4703-8515-8d2497613fc6)

测试了亮色、暗色两个按钮都崩溃了，每次都要卸载重装才能解决问题（也许可以删除配置文件解决，没有尝试）

**Comment by nashaofu** [comment]
周末电脑硬件坏了，不能正常发版，我这边有已经编译的版本，你看看要不要先使用着，我发正式版本了，你再重新安装
[windows.zip](https://github.com/user-attachments/files/16322852/windows.zip)
[macos.zip](https://github.com/user-attachments/files/16322853/macos.zip)

**Comment by nashaofu** [comment]
https://github.com/shell360/release/releases/tag/v0.0.8 已发布最新版本
