### ISSUE TITLE
SFTP无法切换目录或未跟随当前终端的目录路径

### ISSUE THREAD

**Issue by xinlingqudongX** [shell360/release#9]
### 基础信息
- 版本：0.1.1
- 截图：
![image](https://github.com/user-attachments/assets/474cdda8-d7eb-4ac6-ab64-9469a27b5d8f)

### 说明
- 点击SFTP按钮打开的文件目录管理弹窗，当点击路径时只能刷新，不能输入其他路径切换（可忽略）
- 当弹窗的目录不能切换时应跟随当前终端的路径，但是终端路径更改后文件管理弹窗的路径未变更

**Comment by nashaofu** [comment]
第一点，路径的每一部分都可点击，例如可以点击路径中的/到达根目录，第二点，确实没有做同步

**Comment by xinlingqudongX** [comment]
> 第一点，路径的每一部分都可点击，例如可以点击路径中的/到达根目录，第二点，确实没有做同步

或者你唤起winSCP怎么样，就不需要搞文件管理了

**Comment by nashaofu** [comment]
我这个是跨平台软件，所以不会这样做
